package template

import (
	"fmt"
	"path"
	"strings"

	m "github.com/gsiems/db-dictionary/model"
)

func pageHeader(i int, md *m.MetaData) string {

	b := ""

	// resolve the css files
	var css []string
	if md.Cfg.CSSFiles != "" {
		x := strings.Split(md.Cfg.CSSFiles, ",")
		for _, v := range x {
			css = append(css, path.Base(v))
		}
	}
	// if no custom css specified then use the default
	if len(css) == 0 {
		css = append(css, "blues.css")
	}

	switch i {
	case 1, 2:
		ri := ""
		si := ""

		switch i {
		case 1:
			ri = "../"
			si = ""
		case 2:
			ri = "../../"
			si = "../"
		}

		dom := ""
		if len(md.Domains) > 0 {
			dom = `
      <a href="` + si + `domains.html">Domains</a>`
		}

		deps := ""
		if len(md.Dependencies) > 0 {
			dom = `
      <a href="` + si + `dependencies.html">Dependencies</a>`
		}

		//class="active"

		var ci []string
		for _, v := range css {
			ci = append(ci, `    <link rel="stylesheet" href="`+ri+`css/`+v+`" type="text/css">`)
		}

		b = fmt.Sprintf(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{{.Title}}</title>
`+strings.Join(ci, "\n")+`
    <script type="text/javascript" src="`+ri+`js/filter.js"></script>
    <script type="text/javascript" src="`+ri+`js/sort.js"></script>
  </head>
  <body>
    <div id="topNav">
      <a href="`+ri+`index.html">Schemas</a>
      <a href="`+si+`columns.html">Columns</a>
      <a href="`+si+`constraints.html">Constraints</a>%s%s
      <a href="`+si+`tables.html">Tables</a>
      <a href="`+si+`odd-things.html">Odd things</a>
    </div>`, dom, deps)

	default:

		var ci []string
		for _, v := range css {
			ci = append(ci, `    <link rel="stylesheet" href="css/`+v+`" type="text/css">`)
		}

		b = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{{.Title}}</title>
` + strings.Join(ci, "\n") + `
    <script type="text/javascript" src="js/filter.js"></script>
    <script type="text/javascript" src="js/sort.js"></script>
  </head>
  <body>
<!--    <div id="topNav">
      <a class="active" href="index.html">Schemas</a>
    </div> -->`
	}

	return b
}

func sectionHeader(s string) string {
	return fmt.Sprintf(`
      <h2>%s</h2>`, s)
}

func pageFooter(i int, md *m.MetaData) string {

	var js []string

	if md.Cfg.JSFiles != "" {

		ri := ""

		switch i {
		case 1:
			ri = "../"
		case 2:
			ri = "../../"
		}

		// resolve the js files
		x := strings.Split(md.Cfg.JSFiles, ",")
		for _, v := range x {
			js = append(js, `    <script type="text/javascript" src="`+ri+`js/`+path.Base(v)+`"></script>`)
		}
	}

	return fmt.Sprintf(`
    </div>
    <div id="pageFoot">Generated by <a href="https://github.com/gsiems/db-dictionary">db-dictionary</a></div>
    <br />
` + strings.Join(js, "\n") + `
  </body>
</html>
`)

}

func reportHead(showSchema, showTable, showRowcount, showFilter bool) string {

	var schemaTxt string
	var tableTxt string
	var rowCount string
	var filter string

	if showSchema {
		schemaTxt = `
        <div class="headingLabel">Schema:</div><div class="headingItem">{{.SchemaName}}</div>{{if .SchemaComment}}
        <div class="headingLabel"></div><div class="headingItem">{{.SchemaComment|safeHTML}}</div>{{end}}`
	}
	if showTable {
		tableTxt = `
        <div class="headingLabel">Table:</div><div class="headingItem">{{.TableName}}</div>
        <div class="headingLabel">Table Type:</div><div class="headingItem">{{.TableType}}</div>{{if .TableComment}}
        <div class="headingLabel"></div><div class="headingItem">{{.TableComment|safeHTML}}</div>{{end}}`
	}
	if showRowcount {
		rowCount = `
        <div class="headingLabel">Row Count:</div><div class="headingItem">{{.RowCount}}</div>`
	}

	if showFilter {
		filter = `
        <div class="headingLabel">Filter:</div><div class="headingItem"><form id="filter-form" onsubmit="return false;"><input name="filter" id="filterBy" value="" maxlength="32" size="32" type="text" onkeyup="filterTables()"></form></div>`
	}

	return `
    <div id="pageHead"><h1>{{.Title}}</h1>
      <div class="headingContainer">
        <div class="headingLabel">Generated:</div><div class="headingItem">{{.TmspGenerated}}</div>{{if .DBMSVersion}}
        <div class="headingLabel">Database Version:</div><div class="headingItem">{{.DBMSVersion}}</div>{{end}}
        <div class="headingLabel">Database:</div><div class="headingItem">{{.DBName}}</div>{{if .DBComment}}
        <div class="headingLabel"></div><div class="headingItem">{{.DBComment|safeHTML}}</div>{{end}}` + schemaTxt + tableTxt + rowCount + filter + `
      </div>
    </div>`
}

func tpltSchemas() string {
	return reportHead(false, false, false, true) + `
    <div id="pageBody">
      <br/>
      <table width="100.0%" id="dataTableSchema" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Schema</th>
            <th data-type="string">Owner</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Schemas}}
          <tr id="h{{$i|fmtRownum}}">
            <td><a href="{{$v.Name}}/tables.html">{{$v.Name}}</a></td>
            <td>{{$v.Owner}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableSchema.onclick = function(e) {
        sortTable(dataTableSchema, e);
      };
      </script>
      <br />`
}

func tpltSchemaTables() string {
	return reportHead(true, false, false, true) + `
    <div id="pageBody">
      <br/>
      <table width="100.0%" id="dataTableTab" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Owner</th>
            <th data-type="string">Type</th>
            <th data-type="number">Rows</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Tables}}
          <tr id="g{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.Name}}.html">{{$v.Name}}</a></td>
            <td>{{$v.Owner}}</td>
            <td>{{$v.TableType}}</td>
            <td class="tcn">{{$v.RowCount}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableTab.onclick = function(e) {
        sortTable(dataTableTab, e);
      };
      </script>
      <br />`
}

func tpltSchemaDependencies() string {
	return reportHead(true, false, false, false) + `
    <div id="pageBody">
      <br/>
      {{ if .Files }}{{range .Files}}<a href="{{.File}}">{{.Format}}</a><br /> {{end}}
      <img width="100%" class="graph-image" src="dependencies.svg">{{end}}
      <br />`
}

func tpltSchemaDomains() string {
	return reportHead(true, false, false, true) + `
    <div id="pageBody">
      <br/>
      <table width="100.0%" id="dataTableDom" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Name</th>
            <th data-type="string">Data Type</th>
            <th data-type="string">Default</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Domains}}
          <tr id="e{{$i|fmtRownum}}">
            <td>{{$v.Name}}</td>
            <td>{{$v.DataType}}</td>
            <td>{{$v.Default}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableDom.onclick = function(e) {
        sortTable(dataTableDom, e);
      };
      </script>
      <br />`
}

func tpltSchemaColumns() string {
	return reportHead(true, false, false, true) + `
    <div id="pageBody">
      <br/>
      <table width="100.0%" id="dataTableCol" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Column</th>
            <th data-type="number">Position</th>
            <th data-type="string">Data Type</th>
            <th data-type="string">Nulls</th>
            <th data-type="string">Default</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Columns}}
          <tr id="d{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.Name}}</td>
            <td class="tcn">{{$v.OrdinalPosition}}</td>
            <td>{{$v.DataType}}</td>
            <td class="tcc">{{$v.IsNullable|checkMark}}</td>
            <td>{{$v.Default}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableCol.onclick = function(e) {
        sortTable(dataTableCol, e);
      };
      </script>
      <br />`
}

func tpltSchemaConstraintsHeader() string {
	return reportHead(true, false, false, true) + `
    <div id="pageBody">`
}

func tpltSchemaCheckConstraints() string {
	return `
      <table width="100.0%" id="dataTableChk" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Constraint</th>
            <th data-type="string">Search Condition</th>
            <th data-type="string">Status</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .CheckConstraints}}
          <tr id="c{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.Name}}</td>
            <td>{{$v.CheckClause}}</td>
            <td>{{$v.Status}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableChk.onclick = function(e) {
        sortTable(dataTableChk, e);
      };
      </script>
      <br />`
}

func tpltSchemaUniqueConstraints() string {
	return `
      <table width="100.0%" id="dataTableUniq" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Constraint</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Status</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .UniqueConstraints}}
          <tr id="g{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.Name}}</td>
            <td>{{$v.Columns}}</td>
            <td>{{$v.Status}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableUniq.onclick = function(e) {
        sortTable(dataTableUniq, e);
      };
      </script>
      <br />`
}

func tpltSchemaFKConstraints() string {
	return `
      <table width="100.0%" id="dataTableFK" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Constraint</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Is Indexed</th>
            <th data-type="string">Referenced Table</th>
            <th data-type="string">Referenced Columns</th>
            <th data-type="string">On Update</th>
            <th data-type="string">On Delete</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .ParentKeys}}
          <tr id="f{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.Name}}</td>
            <td>{{$v.TableColumns}}</td>
            <td class="tcc">{{$v.IsIndexed|checkMark}}</td>
            <td>{{$v.RefSchemaName}}.<a href="../{{$v.RefSchemaName}}/tables/{{$v.RefTableName}}.html">{{$v.RefTableName}}</a>
            <td>{{$v.RefTableColumns}}</td>
            <td>{{$v.UpdateRule}}</td>
            <td>{{$v.DeleteRule}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableFK.onclick = function(e) {
        sortTable(dataTableFK, e);
      };
      </script>
      <br />`
}

func tpltTableHead(tabType string) string {

	switch tabType {
	case "TABLE", "BASE TABLE", "MATERIALIZED VIEW":
		return reportHead(true, true, true, true) + `
    <div id="pageBody">`
	}

	return reportHead(true, true, false, true) + `
    <div id="pageBody">`

}

func tpltTableColumns(tabType string) string {
	switch tabType {
	case "VIEW", "BASE TABLE", "MATERIALIZED VIEW":
		return `
      <table width="100.0%" id="dataTableCol" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Column</th>
            <th data-type="number">Position</th>
            <th data-type="string">Data Type</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Columns}}
          <tr id="j{{$i|fmtRownum}}">
            <td>{{$v.Name}}</td>
            <td class="tcn">{{$v.OrdinalPosition}}</td>
            <td>{{$v.DataType}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableCol.onclick = function(e) {
        sortTable(dataTableCol, e);
      };
      </script>
      <br />`
	default:
		return `
      <table width="100.0%" id="dataTableCol" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Column</th>
            <th data-type="number">Position</th>
            <th data-type="string">Data Type</th>
            <th data-type="string">Nulls</th>
            <th data-type="string">Default</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Columns}}
          <tr id="j{{$i|fmtRownum}}">
            <td>{{$v.Name}}</td>
            <td class="tcn">{{$v.OrdinalPosition}}</td>
            <td>{{$v.DataType}}</td>
            <td class="tcc">{{$v.IsNullable|checkMark}}</td>
            <td>{{$v.Default}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        <tbody>
      </table>
      <script>
      dataTableCol.onclick = function(e) {
        sortTable(dataTableCol, e);
      };
      </script>
      <br />`
	}
}

func tpltTableConstraintsHeader() string {
	return `
      <table width="100.0%" id="dataTableCons" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Name</th>
            <th data-type="string">Type</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Search Condition</th>
            <th data-type="string">Status</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>`
}

func tpltTableConstraintsFooter() string {
	return `
        </tbody>
      </table>
      <script>
      dataTableCons.onclick = function(e) {
        sortTable(dataTableCons, e);
      };
      </script>
      <br />`
}

func tpltTableCheckConstraints() string {
	return `{{range $i, $v := .CheckConstraints}}
          <tr id="cb{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.Name}}</td>
            <td class="tcnw">Check</td>
            <td class="tcnw"></td>
            <td class="tcnw">{{$v.CheckClause}}</td>
            <td class="tcnw">{{$v.Status}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}`
}

func tpltTablePrimaryKey() string {
	return `{{range $i, $v := .PrimaryKeys}}
          <tr id="ca{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.Name}}</td>
            <td class="tcnw">Primary Key</td>
            <td class="tcnw">{{$v.Columns}}</td>
            <td class="tcnw"></td>
            <td class="tcnw"></td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}`
}

func tpltTableUniqueConstraints() string {
	return `{{range $i, $v := .UniqueConstraints}}
          <tr id="cc{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.Name}}</td>
            <td class="tcnw">Unique</td>
            <td class="tcnw">{{$v.Columns}}</td>
            <td class="tcnw"></td>
            <td class="tcnw"></td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}`
}

func tpltTableIndexes() string {
	return `
      <table width="100.0%" id="dataTableIdx" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Name</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Is Unique</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Indexes}}
          <tr id="n{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.Name}}</td>
            <td class="tcnw">{{$v.IndexColumns}}</td>
            <td class="tcc">{{$v.IsUnique|checkMark}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableIdx.onclick = function(e) {
        sortTable(dataTableIdx, e);
      };
      </script>
      <br />`
}

func tpltTableParentKeys() string {
	return `
      <h3>Parents (references)</h3>
      <table width="100.0%" id="dataTableParent" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Name</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Is Indexed</th>
            <th data-type="string">Referenced Table</th>
            <th data-type="string">Referenced Columns</th>
            <th data-type="string">On Update</th>
            <th data-type="string">On Delete</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .ParentKeys}}
          <tr id="o{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.Name}}</td>
            <td>{{$v.TableColumns}}</td>
            <td class="tcc">{{$v.IsIndexed|checkMark}}</td>
            <td class="tcnw">{{$v.RefSchemaName}}.<a href="../../{{$v.RefSchemaName}}/tables/{{$v.RefTableName}}.html">{{$v.RefTableName}}</a></td>
            <td>{{$v.RefTableColumns}}</td>
            <td>{{$v.UpdateRule}}</td>
            <td>{{$v.DeleteRule}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableParent.onclick = function(e) {
        sortTable(dataTableParent, e);
      };
      </script>
      <br />`
}

func tpltTableChildKeys() string {
	return `
      <h3>Children (referenced by)</h3>
      <table width="100.0%" id="dataTableChild" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Name</th>
            <th data-type="string">Columns</th>
            <th data-type="string">Referencing Table</th>
            <th data-type="string">Referencing Columns</th>
            <th data-type="string">Is Indexed</th>
            <th data-type="string">On Update</th>
            <th data-type="string">On Delete</th>
            <th data-type="string">Comment</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .ChildKeys}}
          <tr id="i{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.RefConstraintName}}</td>
            <td>{{$v.RefTableColumns}}</td>
            <td class="tcnw">{{$v.SchemaName}}.<a href="../../{{$v.SchemaName}}/tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.TableColumns}}</td>
            <td class="tcc">{{$v.IsIndexed|checkMark}}</td>
            <td>{{$v.UpdateRule}}</td>
            <td>{{$v.DeleteRule}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableChild.onclick = function(e) {
        sortTable(dataTableChild, e);
      };
      </script>
      <br />`

}

//      <h2>Dependencies</h2>
func tpltTableDependencies() string {
	return `
      <h3>Parents (this depends on)</h3>
      <table width="100.0%" id="dataTableTdo" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Object Schema</th>
            <th data-type="string">Object Name</th>
            <th data-type="string">Object Type</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Dependencies}}
          <tr id="k{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.DepObjectSchema}}</td>
            <td class="tcnw">{{ if .DepIsLinkable }}<a href="../../{{$v.DepObjectSchema}}/tables/{{$v.DepObjectName}}.html">{{$v.DepObjectName}}</a>{{else}}{{$v.DepObjectName}}{{end}}</td>
            <td class="tcnw">{{$v.DepObjectType}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableTdo.onclick = function(e) {
        sortTable(dataTableTdo, e);
      };
      </script>
      <br />`

}

func tpltTableDependents() string {
	return `
      <h3>Children (depends on this)</h3>
      <table width="100.0%" id="dataTableDot" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Object Schema</th>
            <th data-type="string">Object Name</th>
            <th data-type="string">Object Type</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .Dependents}}
          <tr id="l{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.ObjectSchema}}</td>
            <td class="tcnw">{{ if .IsLinkable }}<a href="../../{{$v.ObjectSchema}}/tables/{{$v.ObjectName}}.html">{{$v.ObjectName}}</a>{{else}}{{$v.ObjectName}}{{end}}</td>
            <td class="tcnw">{{$v.ObjectType}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableDot.onclick = function(e) {
        sortTable(dataTableDot, e);
      };
      </script>
      <br />`
}

func tpltTableFDW() string {
	return `
      <h2>Foreign Data Wrapper</h2>
      <table width="100.0%" id="dataTableFDW" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Wrapper Name</th>
            <th data-type="string">Server Name</th>
            <th data-type="string">Wrapper Options</th>
            <th data-type="string">Comments</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .ForeignWrappers}}
          <tr id="m{{$i|fmtRownum}}">
            <td class="tcnw">{{$v.WrapperName}}</td>
            <td>{{$v.ServerName}}</td>
            <td>{{$v.WrapperOptions}}</td>
            <td>{{$v.Comment|safeHTML}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableFDW.onclick = function(e) {
        sortTable(dataTableFDW, e);
      };
      </script>
      <br />`
}

func tpltTableQuery() string {
	return `
      <pre>
{{.Query}}
      </pre>`
}

func tpltOddHeader() string {
	return reportHead(true, false, false, true) + `
    <div id="pageBody">`
}

func tpltOddTables() string {
	return `
      <table width="100.0%" id="dataTableTab" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">No PK</th>
            <th data-type="string">No indices</th>
            <th data-type="string">Duplicate indices</th>
            <th data-type="string">Only one column</th>
            <th data-type="string">No data</th>
            <th data-type="string">No relationships</th>
            <th data-type="string">Denormalized?</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .OddTables}}
          <tr id="b{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td class="tcc">{{$v.NoPK|checkMark}}</td>
            <td class="tcc">{{$v.NoIndices|checkMark}}</td>
            <td class="tcc">{{$v.DuplicateIndices|checkMark}}</td>
            <td class="tcc">{{$v.OneColumn|checkMark}}</td>
            <td class="tcc">{{$v.NoData|checkMark}}</td>
            <td class="tcc">{{$v.NoRelationships|checkMark}}</td>
            <td class="tcc">{{$v.Denormalized|checkMark}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableTab.onclick = function(e) {
        sortTable(dataTableTab, e);
      };
      </script>
      <br />`
}

func tpltOddColumns() string {
	return `
      <table width="100.0%" id="dataTableCol" class="dataTable">
        <thead>
          <tr>
            <th data-type="string">Table</th>
            <th data-type="string">Column</th>
            <th data-type="string">Nullable and part of a unique index or constraint</th>
            <th data-type="string">Nullable with a default value</th>
            <th data-type="string">Defaults to NULL or 'NULL'</th>
          </tr>
        </thead>
        <tbody>{{range $i, $v := .OddColumns}}
          <tr id="a{{$i|fmtRownum}}">
            <td><a href="tables/{{$v.TableName}}.html">{{$v.TableName}}</a></td>
            <td>{{$v.ColumnName}}</td>
            <td class="tcc">{{$v.NullUnique|checkMark}}</td>
            <td class="tcc">{{$v.NullWithDefault|checkMark}}</td>
            <td class="tcc">{{$v.NullAsDefault|checkMark}}</td>
          </tr>{{end}}
        </tbody>
      </table>
      <script>
      dataTableCol.onclick = function(e) {
        sortTable(dataTableCol, e);
      };
      </script>
      <br />`
}
