package view

func header() string {
	return `<!DOCTYPE html>
<html>
  <head>
    <title>{{.Title}}</title>
    <meta http-equiv="Content-Type" content="utf-8" />
    <link rel="stylesheet" href="{{.PathPrefix}}css/main.css" type="text/css">
  </head>
`
}

func footer() string {
	return `
    </div>
    <div id="PageFoot">Generated by db-dictionary<br/>
      <a href="https://github.com/gsiems/db-dictionary">Github page</a>
    </div>
    <br />
  </body>
</html>
`
}

func css() string {
	return `
body {
    background-color: white;
    font-family: verdana,helvetica,sans-serif;
    margin: 0;
    padding: 0;
}
h1 {
    border-bottom-style: solid;
    border-bottom-width: 2px;
    color: #eee;
    font-size: 150%;
    font-weight: bold;
    margin-top: 0;
    padding-bottom: 0.5ex;
}
h2 {
    border-bottom-style: solid;
    border-bottom-width: 2px;
    color: #009ace;
    font-size: 140%;
    padding-bottom: 0.5ex;
}
#NavBar ul {
    background-color: #003366;
    color: white;
    float: left;
    margin-left: 0;
    padding-left: 0;
    width: 100%;
}
#NavBar ul li {
    display: inline;
}
#NavBar ul li a {
    background-color: #003366;
    border-right: 1px solid #fff;
    color: white;
    float: left;
    padding: 0.2em 1em;
    text-decoration: none;
}
#NavBar ul li a:hover {
    background-color: #336699;
    color: #fff;
}
#PageHead {
    background-color: #009ace;
    border-bottom: 2px solid #999;
    border-color: #999;
    color: #eee;
    margin-bottom: 10px;
    padding-bottom: 5px;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 5px;
}
#PageHead table th {
    color: #eee;
    text-align: left;
    vertical-align: top;
    white-space: nowrap;
}
#PageHead table tr {
    color: #eee;
    text-align: left;
    vertical-align: top;
}
#PageBody {
    font-size: 90%;
    margin-bottom: 10px;
    margin-left: 10px;
    margin-right: 10px;
}
#PageFoot {
    background-color: #009ace;
    color: #eee;
    border-bottom: 2px solid #999;
    border-top: 2px solid #999;
    font-size: 90%;
    font-weight: bold;
    margin-top: 10px;
    padding: 2px 7px 2px 2px;
    text-align: right;
}
#filter-form {
    color: #eee;
    padding-bottom: 1.0ex;
    padding-top: 0.5ex;
}
/* TC1: Standard table text cells */
.TC1 {
    padding-left: 4px;
    padding-right: 4px;
    vertical-align: top;
}
/* TC2: Non-wrapping table text cells */
.TC2 {
    padding-left: 4px;
    padding-right: 4px;
    vertical-align: top;
    white-space: nowrap;
}
/* TCn: Numeric table cells. Note that this is probably backwards for RTL languages. */
.TCn {
    padding-left: 4px;
    padding-right: 8px;
    text-align: right;
    vertical-align: top;
    white-space: nowrap;
}
table.tablesorter {
    border-bottom: 1px solid #777;
    border-left: 1px solid #777;
    border-right: 1px solid #777;
    text-align: left;
    vertical-align: top;
    width: 100%;
}
table.tablesorter thead tr th {
    background-color: #ddd;
    background-position: right center;
    background-repeat: no-repeat;
    border-bottom: 2px solid #777;
    border-color: #777;
    color: #009ace;
    cursor: pointer;
    padding-left: 4px;
    padding-right: 15px;
}
table.tablesorter thead tr .headerSortDown {
    background-color: #bfbfbf;
    background-image: url("../img/desc.gif");
}
table.tablesorter thead tr .headerSortUp {
    background-color: #bfbfbf;
    background-image: url("../img/asc.gif");
}
table.tablesorter tr:nth-child(odd) {
    background-color: #eee;
    color: #333;
}
table.tablesorter tr:nth-child(even) {
    background-color: #ddd;
    color: #333;
}
.mono {
    background-color: #eee;
    color: #333;
    padding: 5px;
    font-family: Bitstream Vera Sans Mono, Consolas, Courier New, DejaVu Sans Mono, Liberation Mono, Lucida Console, Monaco, monospace;
}
`
}

/*
  <div id="ReportHeader"><h1>[% title %]</h1>
    <table class="pageheader">
      <tr><th>Generated:</th><td>[% run_timestamp %]</td></tr>
      <tr><th>Database Version:</th><td>[% database_version %]</td></tr>
      <tr><th>Database:</th><td>[% database_name %]</td></tr>
      [% IF database_comment %]<tr><th>Database Comment:</th><td><div class="comments">[% database_comment %]</div></td></tr>[% END %]
      [% IF schema_name  && schema_name != '' %]<tr><th>Schema:</th><td>[% schema_name %]</td></tr>
        [% IF schema_comment %]<tr><th>Schema Comment:</th><td><div class="comments">[% schema_comment %]</div></td></tr>[% END %]
      [% END %]
      [% IF table_name && table_name != '' %]<tr><th>Table Name:</th><td>[% table_name %]</td></tr>
      <tr><th>Table Type:</th><td>[% table_type %]</td></tr>
      <tr><th>Table Comment:</th><td><div class="comments">[% table_comment %]</div></td></tr>
      <tr><th>Row Count:</th><td>[% row_count %]</td></tr>
      [% END %]
      [% UNLESS no_js %][% UNLESS no_filter %]<tr><th>Filter: </th><td><form id="filter-form"><input name="filter" id="filter" value="" maxlength="32" size="32" type="text"></form></td></tr>[% END %][% END %]
    </table>
  </div>


*/
